# services/npy_loader.py
from __future__ import annotations

import logging
import os

import numpy as np

from utils.analysis_paths import height_filename

log = logging.getLogger(__name__)

"""
Functions to load .npy from ./output.

Expected file tree (names generated by the C++ backend; see
utils/analysis_paths.py):
    ./output/
        <dataset_name>/
            <dataset_name>_height.npy
            <dataset_name>_pixel_y<Y>_x<X>.npy
            ...
"""


def get_base_folder() -> str:
    """
    Return the absolute path to the output folder, resolved at call time.

    Computing this lazily (not at import time) ensures the correct path even
    when the working directory changes after the module is first imported,
    e.g. when running from different launch scripts or test harnesses.
    """
    return os.path.abspath(os.path.join(os.getcwd(), "output"))


def list_datasets() -> list[str]:
    """
    Lists folders of datasets in the output folder.

    Each folder is considered a dataset if it is a directory

    Returns
    -------
    list[str]
        Sorted list of folder names.
    """
    folder = get_base_folder()
    if not os.path.isdir(folder):
        # Soft exception: return empty list and log a warning
        log.warning('Base folder "%s" does not exist.', folder)
        return []

    items = [f for f in os.listdir(folder) if os.path.isdir(os.path.join(folder, f))]
    return sorted(items)


def load_height(dataset_name: str) -> tuple[np.ndarray, str]:
    """
    Loads a dataset heightmap

    Expected file:
        ./output/<dataset_name>/<dataset_name>_height.npy

    Parameters
    ----------
    dataset_name : str
        Dataset folder name.

    Returns
    -------
    (height_array, height_path) : (np.ndarray, str)
        - height_array: numpy array
        - height_path : absolute path to .npy

    Raises
    ------
    FileNotFoundError
        If folder or heightmap file do not exist
    """
    dataset_path = os.path.join(get_base_folder(), dataset_name)
    if not os.path.isdir(dataset_path):
        raise FileNotFoundError(f"Dataset folder not found: {dataset_path}")

    height_path = os.path.join(dataset_path, height_filename(dataset_name))
    if not os.path.isfile(height_path):
        raise FileNotFoundError(f"Height file not found: {height_path}")

    # Eager load, deliberately NOT mmap_mode="r": the returned array is
    # retained by the results view for as long as it is displayed, and on
    # Windows a live mmap keeps the file locked, which makes the backend's
    # delete+rename publish step fail when the same dataset is re-analyzed.
    # The memory cost is irrelevant — the tilt correction materializes a
    # full-size float copy anyway.
    height = np.load(height_path)

    return height, height_path
