# utils/analysis_paths.py
"""
Naming conventions for the analysis output files under ./output/<dataset>/.

These filenames are GENERATED by the C++ backend:
- backend/analysis/src/analysis_api.cpp and utils.cpp write
  "<dataset>_height.npy".
- backend/analysis/src/reconstruction.cpp writes
  "<dataset>_pixel_y<Y>_x<X>.npy" for each saved pixel plot.

Keep this module in sync with the C++ side; it is the single Python source
for parsing/building those names.
"""

from __future__ import annotations

import re

# Suffix of the heightmap file: <dataset>_height.npy
HEIGHT_SUFFIX = "_height.npy"

# Substring that identifies a representative-pixel file (cheap pre-filter)
PIXEL_FILE_MARKER = "_pixel_y"

# Full pixel-file pattern: <prefix>_pixel_y<Y>_x<X>.npy
# Group 1 = y coordinate, group 2 = x coordinate.
PIXEL_FILE_REGEX = re.compile(r".*_pixel_y(\d+)_x(\d+)\.npy")


def height_filename(dataset_name: str) -> str:
    """Return the heightmap filename for a dataset (e.g. 'foo_height.npy')."""
    return f"{dataset_name}{HEIGHT_SUFFIX}"
