"""
Compute Bayer superpixel weights for the Thorlabs LP126CU color camera
under halogen (broadband) illumination.

Purpose
-------
The LP126CU has a Bayer color filter array (RGGB pattern). When used for
Coherence Scanning Interferometry (CSI), the spatial periodicity of the
Bayer pattern introduces artifacts. One way to mitigate this is to combine
each 2x2 Bayer block into a single "superpixel" with weights that reflect
how much signal each channel actually contributes to the total measurement.

The signal collected by each channel (R, G, B) is the integral of:

    S_channel = integral over wavelength of:
                  Source_spectrum(lambda)
                * IR_filter_transmission(lambda)
                * QE_channel(lambda)

The relative weights are these signals normalised to sum to 1
(with the two green pixels in the Bayer block sharing the green weight).

Inputs
------
- Four CSV files extracted from the Thorlabs datasheet plots:
    * ir_filter_transmission.csv  (wavelength_nm, transmission_percent)
    * qe_red.csv                  (wavelength_nm, qe_percent)
    * qe_green.csv                (wavelength_nm, qe_percent)
    * qe_blue.csv                 (wavelength_nm, qe_percent)
- Blackbody temperature for the halogen source (3200 K for the Olympus
  U-LH100IR tungsten-halogen lamp, 100 W / 12 V).

Output
------
- Plots of the input curves, the source spectrum, and the per-channel
  product Source * Filter * QE.
- Printed numerical weights for the four pixels in a 2x2 RGGB block.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d
from pathlib import Path

# ---------------------------------------------------------------------------
# 1. Configuration
# ---------------------------------------------------------------------------

# Folder where the CSV files live. Adjust if needed.
DATA_DIR = Path(__file__).parent

# Temperature of the halogen source (Kelvin).
# The Olympus U-LH100IR is a 100 W tungsten-halogen lamp.  Halogen lamps run
# hotter than plain incandescent bulbs because the halogen cycle regenerates
# the filament, allowing a higher operating temperature (~3200–3400 K).
# 3200 K is a standard value for tungsten-halogen microscope illuminators;
# update if a measured spectral curve for the U-LH100IR becomes available.
T_SOURCE_K = 3200.0

# Common wavelength grid used after interpolation (nm).
# We restrict to the range where ALL curves are defined to avoid extrapolating.
# The QE plot spans 400-1000 nm and the IR filter plot spans 400-1200 nm,
# so 400-1000 nm is the safe overlap.
WAVELENGTH_MIN_NM = 400.0
WAVELENGTH_MAX_NM = 1000.0
WAVELENGTH_STEP_NM = 1.0  # 1 nm resolution is more than enough

# ---------------------------------------------------------------------------
# 2. Helper: blackbody spectral radiance (Planck's law)
# ---------------------------------------------------------------------------

def planck_spectral_radiance(wavelength_nm: np.ndarray, T_kelvin: float) -> np.ndarray:
    """
    Planck's law: spectral radiance of a blackbody as a function of wavelength.

    Returns radiance in W/(m^2 * sr * m). The absolute scale doesn't matter
    here because we normalize at the end — only the SHAPE of the spectrum
    matters for computing relative channel weights.

    Parameters
    ----------
    wavelength_nm : array of wavelengths in nanometers
    T_kelvin      : temperature in Kelvin

    Returns
    -------
    Spectral radiance (arbitrary units, since we'll normalize).
    """
    # Physical constants
    h = 6.62607015e-34   # Planck constant, J*s
    c = 2.99792458e8     # speed of light, m/s
    k_B = 1.380649e-23   # Boltzmann constant, J/K

    # Convert wavelength to meters for the formula
    wl_m = wavelength_nm * 1e-9

    # Planck's law: B(lambda, T) = (2 h c^2 / lambda^5) * 1 / (exp(hc/(lambda k T)) - 1)
    exponent = (h * c) / (wl_m * k_B * T_kelvin)
    # Guard against overflow at very short wavelengths (large exponent)
    # Using np.expm1 = exp(x) - 1 for numerical stability when needed
    radiance = (2.0 * h * c**2) / (wl_m**5) / np.expm1(exponent)

    return radiance


# ---------------------------------------------------------------------------
# 3. Load and interpolate the camera curves
# ---------------------------------------------------------------------------

def load_curve(csv_path: Path) -> tuple[np.ndarray, np.ndarray]:
    """
    Load a two-column CSV (wavelength_nm, value) and return both as arrays.

    skiprows=1 skips the header row present in all CSV files generated by
    extract_plot_data.py (wavelength_nm, transmission_pct / qe_pct).
    """
    data = np.loadtxt(csv_path, delimiter=",", skiprows=1)
    wavelengths = data[:, 0]
    values = data[:, 1]

    # Sort by wavelength just in case the CSV is not monotonic
    # (WebPlotDigitizer sometimes outputs slightly disordered points)
    order = np.argsort(wavelengths)
    return wavelengths[order], values[order]


def interpolate_to_common_grid(wl_raw: np.ndarray,
                               y_raw: np.ndarray,
                               wl_target: np.ndarray) -> np.ndarray:
    """
    Interpolate a curve onto the common wavelength grid.

    Uses linear interpolation. Values outside the original range are clipped
    to zero, which is the physically reasonable choice for QE and transmission
    (we don't want to invent signal beyond the measured range).
    """
    interp_func = interp1d(
        wl_raw, y_raw,
        kind="linear",
        bounds_error=False,
        fill_value=0.0,  # outside the measured range, assume zero response
    )
    return interp_func(wl_target)


# Build the common wavelength axis
wavelength = np.arange(
    WAVELENGTH_MIN_NM,
    WAVELENGTH_MAX_NM + WAVELENGTH_STEP_NM,
    WAVELENGTH_STEP_NM,
)

# Load each curve
wl_ir, T_ir_raw = load_curve(DATA_DIR / "ir_filter_transmission.csv")
wl_R, QE_R_raw = load_curve(DATA_DIR / "qe_red.csv")
wl_G, QE_G_raw = load_curve(DATA_DIR / "qe_green.csv")
wl_B, QE_B_raw = load_curve(DATA_DIR / "qe_blue.csv")

# Interpolate everything onto the common grid.
# Both QE and transmission are given in PERCENT in the datasheet plots,
# so we divide by 100 to work with fractions (0-1) in the integral.
T_ir = interpolate_to_common_grid(wl_ir, T_ir_raw, wavelength) / 100.0
QE_R = interpolate_to_common_grid(wl_R, QE_R_raw, wavelength) / 100.0
QE_G = interpolate_to_common_grid(wl_G, QE_G_raw, wavelength) / 100.0
QE_B = interpolate_to_common_grid(wl_B, QE_B_raw, wavelength) / 100.0

# ---------------------------------------------------------------------------
# 4. Build the source spectrum and the integrands
# ---------------------------------------------------------------------------

# Source spectrum (blackbody at T_SOURCE_K). Arbitrary units — only shape matters.
S_source = planck_spectral_radiance(wavelength, T_SOURCE_K)

# The detected signal per channel is the integral of:
#    Source(lambda) * Filter(lambda) * QE_channel(lambda) d lambda
#
# Note about units:
#   - The QE curves in the datasheet are given WITHOUT the IR filter,
#     according to the manual (Section 6.2). So we multiply by T_ir here.
#   - We use np.trapezoid (trapezoidal rule) for the numerical integral,
#     which is more than accurate enough at 1 nm resolution.
integrand_R = S_source * T_ir * QE_R
integrand_G = S_source * T_ir * QE_G
integrand_B = S_source * T_ir * QE_B

signal_R = np.trapezoid(integrand_R, wavelength)
signal_G = np.trapezoid(integrand_G, wavelength)
signal_B = np.trapezoid(integrand_B, wavelength)

# ---------------------------------------------------------------------------
# 5. Compute the Bayer superpixel weights
# ---------------------------------------------------------------------------

# In a 2x2 RGGB Bayer block there is 1 R pixel, 2 G pixels, and 1 B pixel.
# Each G pixel individually receives signal_G (not signal_G / 2),
# because the QE curve already describes a single green pixel's response.
#
# We define the weights such that the weighted average:
#     superpixel = w_R * R + w_G1 * G1 + w_G2 * G2 + w_B * B
# uses weights proportional to the signal each pixel collects,
# and the four weights sum to 1.
#
# This means signal_G is counted twice (once for each green pixel),
# which is correct: in the Bayer block there are genuinely two green pixels
# both contributing to the integrated light captured by the block.

total = signal_R + 2.0 * signal_G + signal_B

w_R = signal_R / total
w_G1 = signal_G / total
w_G2 = signal_G / total
w_B = signal_B / total

# ---------------------------------------------------------------------------
# 6. Report
# ---------------------------------------------------------------------------

print("=" * 60)
print(f"Bayer superpixel weights for LP126CU")
print(f"Source: blackbody at {T_SOURCE_K:.0f} K (Olympus U-LH100IR tungsten-halogen)")
print(f"Integration range: {WAVELENGTH_MIN_NM:.0f}–{WAVELENGTH_MAX_NM:.0f} nm")
print("=" * 60)
print(f"  w_R  = {w_R:.4f}")
print(f"  w_G1 = {w_G1:.4f}")
print(f"  w_G2 = {w_G2:.4f}")
print(f"  w_B  = {w_B:.4f}")
print(f"  sum  = {w_R + w_G1 + w_G2 + w_B:.4f}  (sanity check, should be 1.0)")
print("=" * 60)

# Also print the raw signals in case they're useful for diagnostics
print("\nRaw integrated signals (arbitrary units):")
print(f"  signal_R = {signal_R:.4e}")
print(f"  signal_G = {signal_G:.4e}   (per single green pixel)")
print(f"  signal_B = {signal_B:.4e}")

# ---------------------------------------------------------------------------
# 7. Plots for sanity checking
# ---------------------------------------------------------------------------

fig, axes = plt.subplots(3, 1, figsize=(10, 10), sharex=True)

# Top panel: the interpolated input curves
axes[0].plot(wavelength, QE_R * 100, color="red", label="QE Red")
axes[0].plot(wavelength, QE_G * 100, color="green", label="QE Green")
axes[0].plot(wavelength, QE_B * 100, color="blue", label="QE Blue")
axes[0].plot(wavelength, T_ir * 100, color="black", linestyle="--",
             label="IR filter transmission")
axes[0].set_ylabel("Percent (%)")
axes[0].set_title("Interpolated input curves")
axes[0].legend(loc="upper right")
axes[0].grid(True, alpha=0.3)

# Middle panel: source spectrum (normalised so it fits the plot)
axes[1].plot(wavelength, S_source / S_source.max(),
             color="orange", label=f"Blackbody @ {T_SOURCE_K:.0f} K (normalised)")
axes[1].set_ylabel("Relative radiance")
axes[1].set_title("Source spectrum")
axes[1].legend(loc="upper right")
axes[1].grid(True, alpha=0.3)

# Bottom panel: integrand for each channel (this is what actually gets summed)
axes[2].plot(wavelength, integrand_R / integrand_R.max(),
             color="red", label="Red integrand")
axes[2].plot(wavelength, integrand_G / integrand_G.max(),
             color="green", label="Green integrand")
axes[2].plot(wavelength, integrand_B / integrand_B.max() if integrand_B.max() > 0 else integrand_B,
             color="blue", label="Blue integrand")
axes[2].set_xlabel("Wavelength (nm)")
axes[2].set_ylabel("Normalised integrand")
axes[2].set_title("Source × Filter × QE  (each normalised to its own max)")
axes[2].legend(loc="upper right")
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(DATA_DIR / "bayer_weights_analysis.png", dpi=150)
plt.close()

print(f"\nPlot saved to: {DATA_DIR / 'bayer_weights_analysis.png'}")
